#!/usr/bin/env ruby

require "../common/option"
require "../common/command"

type = ARGV.shift
case type
when "join"
  input_files = []
  output_file = "output.mp4"
  scale       = "960:540"
  option{
    on( "-d v" ){|value|
      if Dir.exist?( value )
        Dir::foreach( value ){|name|
          path = "#{value}/#{name}"
          if File.file?( path )
            input_files.push path
          end
        }
      else
        puts "Invalid dir: #{value}"
        exit 1
      end
    }
    on( "-f v" ){|value|
      if File.exist?( value )
        input_files.push value
      else
        puts "Invalid file: #{value}"
        exit 1
      end
    }
    on( "-o v" ){|value|
      output_file = value
    }
    on( "-s v" ){|value|
      scale = value
    }
    parse!( ARGV )
  }
  
  # mp4 => ts
  ts_files = []
  input_files.each_with_index{|input_file, i|
    ts_file = "#{i}.ts"
    status, outputs, errors, command = execute( "ffmpeg -i #{input_file} -c copy -f mpegts -y #{ts_file}", "", false, true )
    puts "#{status} <= #{command}"
    if 0 != status
      puts errors
      exit 2
    end
    ts_files.push "file '#{ts_file}'"
  }
  
  # ts => mp4
  concat_file = "#{output_file}.txt"
  open( concat_file, "w" ){|file|
    file.puts ts_files
  }
  status, outputs, errors, command = execute( "ffmpeg -f concat -i #{concat_file} -vf scale=#{scale} -y #{output_file}", "", false, true )
  puts "#{status} <= #{command}"
  if 0 != status
    puts errors
    exit 2
  end
  
  # delete temporary files
  input_files.each_with_index{|input_file, i|
    File.delete( "#{i}.ts" )
  }
  File.delete( concat_file )
else
  puts "Unknown type: #{type}"
end
